rozšíření přístupnosti wc kabiny o euro klíč
Mapybezbarier/mapybezbarier pull request #14
Opened 2019-03-31 18:47 UTC by northys

![Screenshot from 2019-03-31 20-38-58](https://user-images.githubusercontent.com/2878126/55293366-1de33300-53f6-11e9-9f2b-5df6ff5942b2.png)
![Screenshot from 2019-03-31 20-38-23](https://user-images.githubusercontent.com/2878126/55293367-1de33300-53f6-11e9-9803-39ba52ab8c53.png)

2019-04-01 18:22 UTC, vrbas commented
Rekapitulace osobní domluvy:
1) vyjasnit si zadání s Petrem Hazuzou:
- A - nová hodnota číselníku - tak problém s tím, že tento enum je sdílený, takže se začne hodnota nabízet i na dalších místech (přístupnost vedlejšího vchodu, přístupnost výtahu, přístupnost plošiny); pro účely WC by tedy měl vzniknout nový, samostatný enum
- B - nový atribut (boolean)
2) v obou případech by bylo asi dobré upravit i RDF - to bych kdyžtak udělal já
3) v obou případech pak aktualizovat i Apiary https://github.com/Mapybezbarier/api
4) SQL diff - PK je sekvence: buď ID nastavit přes nextval nebo do diffu přidat i explicitní nastavení sekvence `SELECT pg_catalog.setval('mappable_entity_access_id_seq', 4, true);`

2019-04-01 20:12 UTC, vrbas requested changes
app/Module/Web/SourceDetail/DefaultSourceDetail.php:663
Na tomto místě se setavuje popis pro detail WC v detailu objektu na frontendu. Mělo by tedy stačit klíč překladů doplnit o sufix z té nové boolean hodnoty (Euroklíč: ano/ne) a v překladech pak budou 3 klíče: LockedMappableEntityAccess.eurokeyYes, LockedMappableEntityAccess.eurokeyNo a stávající FreelyaccessibleMappableEntityAccess (u této hodnoty myslím nemá smysl zjišťovat hodnotu booleanu).

2019-04-05 16:11 UTC, northys commented
@vrbas 
1) zvolil jsem cestu nejmenšího odporu, tj. variantu A
2) rád se to naučím
3) co bych měl měnit? podle mě je apiary aktuální, protože tam nejsou vypsané hodnoty enumu
4) tak snad jsem to už udělal správně :)

2019-04-06 10:18 UTC, vrbas commented
@northys Vypadá to dobře a máš pravdu, do Apiary není potřeba s touto úpravou dělat žádné úpravy.

K bodu 2 (RDF): je pořeba upravit předpis v souboru `db-scheme\mapybezbarier.rdf` tak, aby se hodnoty přeložili dle nově vytvořeného číselníku. Stačí udělat 2 věci:

1. vytvořit novou entitu (jako kopii `<#EntityAccess>`) odkazující na nově vytvořenou tabulku
1. tuto novou entitu použít jako `parentTriplesMap` pro atribut `rr:predicate jup:wcCabinAccess`.

Kdyby to nebylo srozumitelné, dej vědět.

2019-05-18 11:02 UTC, northys commented
@vrbas ping, rdf fixed

2019-05-19 08:58 UTC, vrbas commented on db-scheme/mapybezbarier.rdf
> +    rr:logicalTable [ rr:tableName "mappable_entity__wc_cabin_access" ];
Typo `mappable_entity__wc_cabin_access` => `mappable_entity_wc_cabin_access`

Jinak je to ok.

2019-05-20 14:56 UTC, northys commented
@vrbas opraveno, squashnuto. nasadíš to prosím tě? já mám teď firemní macbook a nemám tak rozjetý RDP. mělo by stačit pustit sql a pullnout

2019-05-21 18:57 UTC, vrbas approved these changes

2019-05-21 18:57 UTC, merged