Import vozejkmap wckompas
Mapybezbarier/mapybezbarier pull request #4
Opened 2017-08-09 19:19 UTC by vrbas

2017-08-21 19:22 UTC, vrbas commented
Zavřeno, bude nahrazeno aktuálním.

2017-08-21 21:46 UTC, jaygridley requested changes

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Downloader/DownloaderFactory.php
> + * Slouzi pro zdroje, pro ktere nejsou data prosutpna ciste pres HTTP request
typo ve slove pristupna

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Downloader/WheelmapDownloader.php
> +     * @return array
v rozhranni IDownloader je definovan navratovy typ string, tato implementace vraci array. Rozsirit/zmenit navratovy typ v rozhranni?

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Downloader/WheelmapDownloader.php
> +                $totalPages = $this->getMetadataInfo($data, 'num_pages', 1);
$actualPage i $totalPages bych typecastnul na int

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Downloader/WheelmapDownloader.php
> +                    if ($page == $actualPage) {
porovnaval bych na identitu

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Downloader/WheelmapDownloader.php
> +    public function getContent($url)
je nutna viditelnost public?

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/VozejkmapParser.php
> +            if (preg_match('~(\d+)/?(\d*)(\D*)~', $housenumber, $matches)) {
misto preg_match bych pouzil Strings::match

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/VozejkmapParser.php
> +                if ($matches[1] && !$matches[2] && $matches[3]) {
muze padat na nedefinovanem indexu, osetrit pritomnost vsech indexu

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/VozejkmapParser.php
> +                    $ret['streetDescNo'] = $matches[1] ? $matches[1] : null;
mozno pouzit operator ??

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WcKompasParser.php
> +            throw new ParseException('Data nejsou v očekávaném formátu.');
diakritika v message vyjimky je novinka v kodu, nezavadel bych

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WcKompasParser.php
> +                if (array_key_exists(Arrays::get($attribute, 'attribute_id', null), $this->mapAttribute)) {
volani Arrays::get vytahnout do promenne

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WcKompasParser.php
> +                    $ret[$this->mapAttribute[$attribute['attribute_id']]] = array_pop($arrayValue);
pouzit nove zavedenou promennou

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WcKompasParser.php
> +        $accesibility_value = $this->getRowAttribute($row, self::ACCESSIBILITY_ATTRIBUTE_ID);
underscore notaci v nazvu promenne nepouzivat, pouzivat camelCase

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WcKompasParser.php
> +        $accesibility_value = $this->getRowAttribute($row, self::ACCESSIBILITY_ATTRIBUTE_ID);
typecast na int

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WcKompasParser.php
> +        return (1 == $accesibility_value) ? ObjectMetadata::ACCESSIBILITY_PARTLY : ObjectMetadata::ACCESSIBILITY_NO;
porovnavat na identitu?

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WheelmapParser.php
> +    protected $vozejkmapHashmap;
chybi doc

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WheelmapParser.php
> +            $ret['id'] = Arrays::get($row, 'id', null);
nastaveni ID ma byt podmineno pritomnosti WC?

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WheelmapParser.php
> +            $ret['wheelchair_toilet'] = Arrays::get($row, 'wheelchair_toilet', 'unknown');
pokud prosla podminka, jiz neni potreba volat Arrays::get, ale staci pouze ternarni ?:

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WheelmapParser.php
> +        if (!empty($row['wheelchair'])) {
pristup na $row['wheelchair'] bych zacachoval do promenne, vola se nasledne nekolikrat

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Parser/WheelmapParser.php
> +        return in_array($wheelmapHash, $this->vozejkmapHashmap);
pouzit 3. parametr funkce

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Service/ValuesNormalizer.php
> +            if (is_null($value) || Validators::is($value, 'scalar')) {
misto is_null pouzit identitu s null

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Admin/Component/ImportLogsListControl/template/ImportLogsListControl.detail.latte
> +                    {!Tracy\Dumper::toHtml($item['data'])}
! nepouzivat, je deprecated, pouzit |noescape

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Admin/Service/AutomaticImportService.php
> +        $downloader = $this->downloaderFactory->create($source);
DownloaderFactory bych napsal tak, ze bude vracet DefaultDownloader, pokud neexistuje implementace pro dany zdroj. DefaultDownloader by pak obsahoval kod z else vetve.

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Admin/Service/ManualImportService.php
> +            $downloader = $this->downloaderFactory->create($source);
kdyz zavedeme DefaultDownloader, tak se zbavime tehle duplikace kodu

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/Component/DetailControl/Renderer/WcKompasRenderer/template/WcKompasRenderer.latte
> +        {if !is_null($pictogram['value'])}
misto is_null pouzivat identitu s null

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/Component/DetailControl/Renderer/WcKompasRenderer/template/WcKompasRenderer.latte
> +            {? $key = !empty($pictogram['key']) ? $pictogram['key'] : $key;}
v Nette 2.4 je {?} depracated a pouziva se {php}

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/Component/DetailControl/Renderer/WheelmapRenderer/template/WheelmapRenderer.latte
> +    <div n:class="detail_pictogram, nwjs_description_opener, !empty($object['custom_data']['wheelchair_toilet']) ? 'accessiblewcmkpo' : (false === $object['custom_data']['wheelchair_toilet'] ? 'inacc
vnoreny ternarni operator, radeji bych data pripravil v PHP, pokud pujde

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/Component/InfoBoxControl/Renderer/WcKompasRenderer/template/WcKompasRenderer.latte
> +{includeblock "../../DefaultRenderer/template/DefaultRenderer.blocks.latte"}
v Nette 2.4 je includeblock deprecated, pouzivat se import

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/SourceDetail/WcKompasSourceDetail.php
> +            $ret['value'] = (1 == $externalData['free']);
2x stejny kod, cachovat v promenne

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/SourceDetail/WcKompasSourceDetail.php
> +            $ret['value'] = (1 == $externalData['accessible']);
2x stejny kod, cachovat v promenne

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/SourceDetail/WcKompasSourceDetail.php
> +            $ret['value'] = (2 == $externalData['always_paid']);
2x stejny kod, cachovat v promenne

2017-08-21 21:46 UTC, jaygridley commented on app/Module/Web/SourceDetail/WheelmapSourceDetail.php
> +        if (isset($externalData['wheelchair_toilet'])) {
opakuje se pristup k indexu pole, cachovat v promenne

2017-08-21 21:46 UTC, jaygridley commented on app/Exchange/Downloader/DownloaderFactory.php
> +        if (isset($this->mapping[$source['format']])) {
pokud sluzba neni v mapovani a neexistuje default, pak bych vyhazoval vyjimku

2017-08-25 09:30 UTC, vrbas commented on app/Exchange/Downloader/WheelmapDownloader.php
> +    public function getContent($url)
Nerozumím. Odpovídá definici v rozhraní a je veřejná metoda pro získání dat.

2017-08-25 10:08 UTC, vrbas commented on app/Module/Web/Component/DetailControl/Renderer/WheelmapRenderer/template/WheelmapRenderer.latte
> +    <div n:class="detail_pictogram, nwjs_description_opener, !empty($object['custom_data']['wheelchair_toilet']) ? 'accessiblewcmkpo' : (false === $object['custom_data']['wheelchair_toilet'] ? 'inacc
V PHP nechci připravovat název CSS třídy. Vnořený ternární operátor v tomto případě podle mě díky menší ukecanosti ve výsledku zvýší čitelnost kódu.

2017-08-25 13:06 UTC, vrbas commented
@jaygridley Díky za detialní CR. Připomínky, které byly jasné, jsem zapracoval. Některé dotazy v komentářích. Další, které nepatří ke konkrétnímu komentáři z CR (můžeme probrat osobně):

- typecast a silné porovnání - k čemu to je, když tím typecastem stejně můžu zanést chybu?
- PHP7 featury - díky za upozornění, branch byla postavena ještě nad PHP 5.6, nebudu tey zpětně měnit; do budoucna budu používat
- DefaultDownloader - přijde mi zbytečné zavádět jen kvůli tomu, abych neduplikoval 1 řádek kódu; pokud by byla nějaká složitější logika, tak samozřejmě souhlas
- "2x stejny kod, cachovat v promenne" - není mi jasný přínos
- includeblock x import - aktuální verze Nette, nad kterou je branch postavená, to bohužel nepodporuje. Musíme až zpětně při mergi s větví dev-nette24

2017-08-25 13:09 UTC, vrbas commented
@zbynek-net I kdybychom featury PHP 7 nepoužívali v našem kódu, stejně nebude možné projekt nad PHP 5.6 rozjet. V rámci upgradu povyšujeme i verzi Nette a dalších používaných knihoven. Některé z nich PHP 7 vyžadují.

2017-08-28 17:46 UTC, jaygridley commented
@vrbas díky za zapracování. K otevřeným dotazům:

* *typecast a silné porovnání* - jsou místa, kde je návratový typ funkce mixed, protože třeba vyzobáváš data z nějaké struktury, no a když dál v kódu víš, že potřebuješ udělat porovnání třeba s integer, nebo ty vyzobnuté data nějak procesuješ a validuješ, tak bych si pro další kód typecastem pomohl. Co se týče identity, tak tu bych používal pokaždé, pokud to není nezbytně nutný opak, což by nemělo snad nemělo nastávat. Jde o to, že takto ti přes kód neteče něco, co neočekáváš. Pak se to špatně hledá.
* *PHP 7 featury* - jasně, spíš šlo o hinty pro další práci
* *DefaultDownloader* - tento kompromis přijímám
* *2x stejny kod, cachovat v promenne* - tak především zjednodušuje refaktoring, přehlednost a je to méně náchylné k chybám. Do spekulací o výkonnosti nad většími strukturami, které by tady v této situaci zrovna asi mohly být, se nebudu pouštět
* *includeblock x import* - opět hint pro další práci

2017-08-29 19:31 UTC, jaygridley approved these changes

2017-09-08 21:02 UTC, merged